apiVersion: v1
kind: Service
metadata:
  name: kf-api-svc
spec:
  selector:
    app: kf-api
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kf-api
  labels:
    app: kf-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kf-api
  template:
    metadata:
      labels:
        app: kf-api
    spec:
      containers:
        - name: kf-api
          image: devinwangg/fastapi-k8s:1.0.0
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          resources:
            - requests:
              cpu: "250m"
